### ISSUE TITLE
Pairing second RWECS never completes

### ISSUE THREAD

**Issue by era95** [Garmin-Race-Walking-App-Developers/Garmin-Race-Walking-App#4]
After attempting to pair a second device, the pairing fails and disconnects any other device that was connected:

<img src="https://github.com/Garmin-Race-Walking-App-Developers/Garmin-Race-Walking-App/assets/94511816/88d2013b-2e64-43e5-9d65-2be62b9377ea"  width="35%">

The devices reset because of this line of code:
https://github.com/Garmin-Race-Walking-App-Developers/Garmin-Race-Walking-App/blob/35a2645a40f6969e29189f959313ce3bd592c299/RwecsConnect/source/ui-delegate/DeviceConnectionProgressDelegate.mc#L40

This functionality is as designed but we probably shouldn't blow away all connections when one fails. Just the connection that was the issue.

Further investigation needs to be done into why the second device never fully establishes connection. But a good path forward would be to change the app so we only unpair the device that failed establishing proper connection. 

commenting out the above line of code causes massive downstream issues. Throwing an error that cannot be caught and forces the runtime to halt:
![image](https://github.com/Garmin-Race-Walking-App-Developers/Garmin-Race-Walking-App/assets/94511816/574e6ce5-bbac-4682-b056-fbb1e9c8ce94)

**Comment by era95** [comment]
This PR addresses the unpairing of all devices:
https://github.com/Garmin-Race-Walking-App-Developers/Garmin-Race-Walking-App/pull/8

**Comment by era95** [comment]
After much extensive research, I'm 90% sure that the inability for the second device to connect is due to the use of a singleton BLE delegate object. I'm hashing out a refactor of the Bluetooth component that will allow for a one to one relationship of delegate objects to devices. I'm hoping to have it ready before the next stakeholder meeting 4/1/2024. 

I will report my findings along the way

**Comment by era95** [comment]
Turns out BLE delegate must be a singleton:
https://developer.garmin.com/connect-iq/api-docs/Toybox/BluetoothLowEnergy.html#setDelegate-instance_function

**Comment by hieumn288** [comment]
Fixed the issue by updating Connect IQ Simulator version to 7.1.0 
Previous versions of Simulator have also caused issues with Bluetooth devices being paired but not connected in the past: https://forums.garmin.com/developer/connect-iq/f/discussion/309232/ciq-simulator-issue-ble-device-not-connected-after-pairing

**Comment by era95** [comment]
Amazing news! Confirmed working locally for me as well. Closing this issue
